dataset:
  data_path: '$ALFWORLD_DATA/json_2.1.1/train'
  eval_id_data_path: '$ALFWORLD_DATA/json_2.1.1/valid_seen'
  eval_ood_data_path: '$ALFWORLD_DATA/json_2.1.1/valid_unseen'
  num_train_games: -1
  num_eval_games: -1

logic:
  domain: '$ALFWORLD_DATA/logic/alfred.pddl'
  grammar: '$ALFWORLD_DATA/logic/alfred.twl2'

env:
  type: 'AlfredTWEnv'
  domain_randomization: False
  task_types: [1, 2, 3, 4, 5, 6]
  expert_timeout_steps: 150
  expert_type: "handcoded"
  goal_desc_human_anns_prob: 0.0

controller:
  type: 'oracle'
  debug: False
  load_receps: True

general:
  random_seed: 42
  use_cuda: True
  visdom: False
  task: 'alfred'
  training_method: 'dagger'
  save_path: './training/'
  observation_pool_capacity: 3
  hide_init_receptacles: False
  training:
    batch_size: 1
    max_episode: 50000
  evaluate:
    run_eval: False
    batch_size: 1
    env:
      type: "AlfredTWEnv"

dagger:
  action_space: "generation"
  max_target_length: 20
  beam_width: 1
  generate_top_k: 1
  training:
    max_nb_steps_per_episode: 50
  fraction_assist:
    fraction_assist_anneal_episodes: 50000
    fraction_assist_anneal_from: 1.0
    fraction_assist_anneal_to: 0.01
  fraction_random:
    fraction_random_anneal_episodes: 0
    fraction_random_anneal_from: 0.0
    fraction_random_anneal_to: 0.0
  replay:
    replay_memory_capacity: 500000
    update_per_k_game_steps: 5
    replay_batch_size: 64
    replay_sample_history_length: 4
    replay_sample_update_from: 2
