"""
utils/action_parser.py

Extract and validate the <action>...</action> span from raw LLM output.
Logic mirrors SkillRL's alfworld_projection.py but is decoupled from Ray/batching.
"""

import re
from typing import Tuple


def parse_action(llm_output: str) -> Tuple[str, bool]:
    """
    Extract the action string from between <action> and </action> tags.

    Rules (matches SkillRL's alfworld_projection):
    - Must have both <think>...</think> AND <action>...</action> tags.
    - Must not contain Chinese characters.
    - Content between <action> tags is lowercased and stripped.

    Args:
        llm_output: Raw text generated by the LLM for one step.

    Returns:
        (action_text, is_valid)
        action_text: Extracted + lowercased action, or last 30 chars of output on failure.
        is_valid:    True iff all validation rules pass.
    """
    text = llm_output

    # ── Extract <action> span ─────────────────────────────────────────────────
    action_match = re.search(r"<action>(.*?)</action>", text, re.IGNORECASE | re.DOTALL)
    if not action_match:
        return text[-30:].strip().lower(), False

    action_text = action_match.group(1).strip().lower()

    # ── Validate <think> tags present ─────────────────────────────────────────
    has_think = bool(re.search(r"<think>.*?</think>", text, re.IGNORECASE | re.DOTALL))
    if not has_think:
        return action_text, False

    # ── No Chinese characters ─────────────────────────────────────────────────
    if re.search(r"[一-鿿]", text):
        return action_text, False

    return action_text, True


def match_admissible(action: str, admissible: list) -> str:
    """
    Fuzzy-match action against the admissible command list.
    Returns the closest admissible command, or the original action if no match.
    This prevents spurious invalid-action penalties for minor whitespace/case diffs.
    """
    if not admissible:
        return action
    action_lower = action.lower().strip()
    # Exact match first
    for cmd in admissible:
        if cmd.lower().strip() == action_lower:
            return cmd
    # Prefix / substring match
    for cmd in admissible:
        if action_lower in cmd.lower() or cmd.lower() in action_lower:
            return cmd
    return action
